[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "ninja",
    "cmake>=3.12"
]
build-backend = "setuptools.build_meta"

[mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.pytest.ini_options]
norecursedirs= "tests/utils"
