// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gL0Learn_fit
Rcpp::List gL0Learn_fit(const arma::mat& Y, arma::mat& theta_init, const double atol, const double rtol, const double M, const double l0, const double l1, const double l2, const size_t max_iter);
RcppExport SEXP _gL0Learn_gL0Learn_fit(SEXP YSEXP, SEXP theta_initSEXP, SEXP atolSEXP, SEXP rtolSEXP, SEXP MSEXP, SEXP l0SEXP, SEXP l1SEXP, SEXP l2SEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< const double >::type atol(atolSEXP);
    Rcpp::traits::input_parameter< const double >::type rtol(rtolSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type l0(l0SEXP);
    Rcpp::traits::input_parameter< const double >::type l1(l1SEXP);
    Rcpp::traits::input_parameter< const double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< const size_t >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(gL0Learn_fit(Y, theta_init, atol, rtol, M, l0, l1, l2, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gL0Learn_gL0Learn_fit", (DL_FUNC) &_gL0Learn_gL0Learn_fit, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_gL0Learn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
