# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_OracleScalarL0L2NoBounds_prox_double <- function(theta, l0, l2) {
    .Call(`_gL0Learn_test_OracleScalarL0L2NoBounds_prox_double`, theta, l0, l2)
}

test_OracleScalarL0L2NoBounds_prox_vec <- function(theta, l0, l2) {
    .Call(`_gL0Learn_test_OracleScalarL0L2NoBounds_prox_vec`, theta, l0, l2)
}

test_OracleVectorL0L2NoBounds_prox_vec <- function(theta, l0, l2) {
    .Call(`_gL0Learn_test_OracleVectorL0L2NoBounds_prox_vec`, theta, l0, l2)
}

test_OracleScalarL0L1L2NoBounds_prox_double <- function(theta, l0, l1, l2) {
    .Call(`_gL0Learn_test_OracleScalarL0L1L2NoBounds_prox_double`, theta, l0, l1, l2)
}

test_OracleScalarL0L1L2NoBounds_prox_vec <- function(theta, l0, l1, l2) {
    .Call(`_gL0Learn_test_OracleScalarL0L1L2NoBounds_prox_vec`, theta, l0, l1, l2)
}

test_OracleVectorL0L1L2NoBounds_prox_vec <- function(theta, l0, l1, l2) {
    .Call(`_gL0Learn_test_OracleVectorL0L1L2NoBounds_prox_vec`, theta, l0, l1, l2)
}

test_OracleScalarL0L2ScalarBounds_prox_double <- function(theta, l0, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleScalarL0L2ScalarBounds_prox_double`, theta, l0, l2, lows, highs)
}

test_OracleScalarL0L2ScalarBounds_prox_vec <- function(theta, l0, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleScalarL0L2ScalarBounds_prox_vec`, theta, l0, l2, lows, highs)
}

test_OracleVectorL0L2ScalarBounds_prox_vec <- function(theta, l0, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleVectorL0L2ScalarBounds_prox_vec`, theta, l0, l2, lows, highs)
}

test_OracleScalarL0L1L2ScalarBounds_prox_double <- function(theta, l0, l1, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleScalarL0L1L2ScalarBounds_prox_double`, theta, l0, l1, l2, lows, highs)
}

test_OracleScalarL0L1L2ScalarBounds_prox_vec <- function(theta, l0, l1, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleScalarL0L1L2ScalarBounds_prox_vec`, theta, l0, l1, l2, lows, highs)
}

test_OracleVectorL0L1L2ScalarBounds_prox_vec <- function(theta, l0, l1, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleVectorL0L1L2ScalarBounds_prox_vec`, theta, l0, l1, l2, lows, highs)
}

test_OracleScalarL0L2VectorBounds_prox_vec <- function(theta, l0, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleScalarL0L2VectorBounds_prox_vec`, theta, l0, l2, lows, highs)
}

test_OracleVectorL0L2VectorBounds_prox_vec <- function(theta, l0, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleVectorL0L2VectorBounds_prox_vec`, theta, l0, l2, lows, highs)
}

test_OracleScalarL0L1L2VectorBounds_prox_vec <- function(theta, l0, l1, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleScalarL0L1L2VectorBounds_prox_vec`, theta, l0, l1, l2, lows, highs)
}

test_OracleVectorL0L1L2VectorBounds_prox_vec <- function(theta, l0, l1, l2, lows, highs) {
    .Call(`_gL0Learn_test_OracleVectorL0L1L2VectorBounds_prox_vec`, theta, l0, l1, l2, lows, highs)
}

gL0Learn_fit <- function(Y, theta_init, atol, rtol, l0, l1, l2, max_iter) {
    .Call(`_gL0Learn_gL0Learn_fit`, Y, theta_init, atol, rtol, l0, l1, l2, max_iter)
}

gL0Learn_psifit <- function(Y, theta_init, atol, rtol, l0, l1, l2, max_iter) {
    .Call(`_gL0Learn_gL0Learn_psifit`, Y, theta_init, atol, rtol, l0, l1, l2, max_iter)
}

