# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_Oracle_prox <- function(theta, l0, l1, l2, lows, highs) {
    .Call(`_gL0Learn_test_Oracle_prox`, theta, l0, l1, l2, lows, highs)
}

is_sympd <- function(x) {
    .Call(`_gL0Learn_is_sympd`, x)
}

gL0Learn_fit_R <- function(Y, theta_init, l0, l1, l2, algorithm, lows, highs, atol, rtol, max_iter) {
    .Call(`_gL0Learn_gL0Learn_fit_R`, Y, theta_init, l0, l1, l2, algorithm, lows, highs, atol, rtol, max_iter)
}

