# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gL0Learn_fit <- function(Y, theta_init, atol, rtol, M, l0, l1, l2, max_iter) {
    .Call(`_gL0Learn_gL0Learn_fit`, Y, theta_init, atol, rtol, M, l0, l1, l2, max_iter)
}

