on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: pre-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install CXX tools
      run: |
        brew install llvm uncrustify cppcheck include-what-you-use
        pip install cpplint
    - uses: pre-commit/action@v3.0.0
