on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: pre-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.1"
    - name: Install CXX tools
      run: |
        sudo apt-get install llvm uncrustify cppcheck
        pip install cpplint
    - uses: pre-commit/action@v3.0.0
