name: Python CI

  # Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        include:
            CC:  gcc-10
            CXX: g++-10
    defaults:
      run:
        working-directory: ./pypkg

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install gL0Learn
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
        env:
          CC: ${{matrix.CC}}
          CXX: ${{matrix.CXX}}

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1