name: Python CI

  # Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    defaults:
      run:
        working-directory: ./pypkg

    runs-on: ubuntu-latest
    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install gL0Learn
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
        env:
          CC: gcc-10
          CXX: g++-10

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1