name: Python CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - "pypkg/**"
      - '.github/workflows/python.yml'

  pull_request:
    branches: [ main ]
    paths:
      - "pypkg/**"
      - '.github/workflows/python.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
        include:
          - os: macos-latest
          - os: ubuntu-latest
            INSTALL_DEPS: |
              sudo apt-get install -y liblapack-dev
              bash scripts/install_linux_libs.sh
            CC:  gcc-10
            CXX: g++-10
    defaults:
      run:
        working-directory: ./pypkg

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: ${{ matrix.INSTALL_DEPS }}

      - name: Install gL0Learn
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"
        env:
          CC: ${{matrix.CC}}
          CXX: ${{matrix.CXX}}

      - name: Test python
        run: |
          pytest tests/
