name: Python Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Pandoc
        run: |
          conda install pandoc
          pip install nbsphinx
          pip install sphinx-rtd-theme
     
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "pypkg/doc/"
